Sprint1/step1
Canfus/react-burger pull request #1
Opened 2023-02-06 12:34 UTC by Canfus

2023-02-06 14:30 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

Приложение начинает обрастать функционалом и уже постепенно проглядывается картина готового продукта.

### **Вы молодец!**

- Декомпозиция файлов по директориям соответствует описанию;
- Сборка и запуск проекта выполняются без ошибок;

### **Но есть несколько замечаний, которые нужно исправить:**

- Нужно очистить проект от лишних файлов, которые остались при инициализации create-react-app.

  - App.test.tsx;

- В компоненте App-header требуется поправить семантику, переделать div в ссылки, а также текст в ссылках, лучше обернуть в `span`, а не в `p`;

- В директории `components` должен быть компонент App. Компонент `App`, он также должен быть в папке (как и другие компоненты). Как правило, это основной компонент в React, который выступает в качестве контейнера для всех остальных компонентов;

- Не стоит писать стили инлайново, в будущем это может затруднить поиск ошибок, и перебить стили заданных классов. Лучше дать какой-то класс, и там указать уже нужные вам стили;

- Если вы начали писать проект на typescript, то должны указывать корректные типы, типа any (в близжайшие нексолько заданий) быть не должно. За помощью можете обращаться к наставникам);

### **Сделает код лучше:**

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: <https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders>

- В некоторых местах нарушено форматирование кода, проблемы с отступами и в некоторых местах слишком длинные строки, что затрудняет чтение кода. Об оформлении кода можно почитать здесь <https://learn.javascript.ru/coding-style>. Постарайтесь использовать автоматическое форматирование, это сильно экономит время. Одно из наиболее популярных дополнений для форматирования кода - Prettier (<https://prettier.io/>)

- Также заметил несколько слов написанных с ошибками. Чтобы это происходило реже попробуйте попользоваться расширением spell checker. <https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker>

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2023-02-06 14:30 UTC, ArslanDev666 commented on src/components/BurgerConstructor/BurgerConstructorItemList/BurgerConstructorItemList.tsx
> +}
**Надо исправить:**

Если вы начали писать проект на typescript, то должны указывать корректные типы, типа any (в близжайшие нексолько заданий) быть не должно.

2023-02-06 14:30 UTC, ArslanDev666 commented on src/components/BurgerConstructor/BurgerConstructor.tsx
> +                    thumbnail={constructorItems.find(item => item.type === 'bun').image_mobile}
**Надо исправить:**

Лучше вынести bun в отдельную переменную, и просто её переиспользовать, не стоит каждый раз делать поиск.
Показал как это лучше сделать в комментарии к `totalPrice`

2023-02-06 14:30 UTC, ArslanDev666 commented on src/components/BurgerIngridients/BurgerIngridients.tsx
> +                <BurgerIngridientsMain {...props} />
**Надо исправить:**

Лучше вместо 3 компонентов, сделать 1 общий компонент и переиспользовать его у раза. 
А также делать фильтрацию ингредиентов заранее, в компоненте `burger-ingredients` и потом просто передавать для рендера готовый массив.

```js
const buns = useMemo(data.filter((item) => item.type === 'bun'), [data]);
const mains = useMemo(data.filter((item) => item.type === 'main'), [data]);
const sauces = useMemo(data.filter((item) => item.type === 'sauce'), [data]);
```

`useMemo` - можете пока не использовать)) но если изучите этот хук, будет отлично)

2023-02-06 14:30 UTC, ArslanDev666 commented on src/App.tsx
> +    }
**Надо исправить:**

Здесь и далее, не стоит такими методами передавать пропсы. Пропсы лучше передавать напрямую, а не делать из них отдельную переменную.

2023-02-06 20:12 UTC, Canfus commented on src/App.tsx
> +    }
Норм если я закомменчу фукнции?

2023-02-06 20:41 UTC, ArslanDev666 commented on src/App.tsx
> +    }
Лучше удалить, чтобы компонент был более чистым)) по коммитам в гитхабе потом сможете восстановить, если понадобится))

2023-02-06 21:02 UTC, Canfus commented on src/App.tsx
> +    }
Хорошо
Еще ранее видел ваше замечание по поводу того, чтобы заменить все `p` на `span`, но что-то сейчас не нахожу

2023-02-08 03:09 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец! Можете приступать к финальному этапу задания)**

- Все замечания с прошлого ревью были исправлены.
- Отметил несколько замечаний в коде) которые нужно будет исправить.

### **Сделает код лучше:**

- Весь неиспользуемый код лучше удалить.

2023-02-08 03:09 UTC, ArslanDev666 commented on src/components/App/App.tsx
> +interface ConstructorItem {
**Можно лучше:**

Лучше назвать `IngredientType`

2023-02-08 03:09 UTC, ArslanDev666 commented on src/components/BurgerConstructor/BurgerConstructor.tsx
> +}
**Надо исправить:**

Тут будет другой тип (тип ингредиента, который у вас сейчас в компоненте `app`)

```js
interface BurgerConstructorProps {
    data: ConstructorItem[],
}
```

2023-02-08 03:09 UTC, ArslanDev666 commented on src/components/BurgerConstructor/BurgerConstructor.tsx
> +                </div>
**Надо исправить:**

Вы также должны выводить ингредиенты, а не только булки))

https://disk.yandex.com/i/xeN-lbWY0mNwkw.

2023-02-08 06:53 UTC, Canfus commented on src/components/App/App.tsx
> +    const [constructorItems, setConstructorItems] = useState<ConstructorItem[]>([data.find(item => item.type === 'bun')]
Аргументирую это тем, что в дальнейшем это состояние будет использоваться в функционале, который вы попросили меня удалить 💀

2023-02-08 06:57 UTC, merged